### ISSUE TITLE
Mac - Taskbar icon always present

### ISSUE THREAD

**Issue by camhart** [dorkbox/SystemTray#108]
I want a system tray icon, with no task bar icon in Mac OSX.  Unfortunately the instant SystemTray.get() is called, the task bar icon appears.  Is there anyway to prevent that?

**Comment by camhart** [comment]
Setting System.setPropery("apple.awt.UIElement", "true"); fixed the issue.

**Comment by Tristan971** [comment]
For next times, just know that the "task bar" is called the dock, I saw this but didn't know what it was on reading it :-) 

Other than that, indeed this sets `LSUIElement` to `true` and accomplishes what you wanted

**Comment by danielemaddaluno** [comment]
I'm using and testing my code with macOS Mojave version 10.14.4.
I would like to reopen this issue because I'm trying to make the dock icon to disappear inside a JavaFX application (a simple tray application with no dock icon).

I started from the code [TestTrayJavaFX.java](https://github.com/dorkbox/SystemTray/blob/master/test/dorkbox/TestTrayJavaFX.java) and I added the `System.setProperty("apple.awt.UIElement", "true");` line at the top of the main method but this doesn't work.

So I tried to solve my problem like this, mixing JavaFX and a "dockless" SystemTray, I tried with this code that apparently works fine:

```
public class AppAwt {
	public static void main(String[] args) throws Exception {
		System.setProperty("apple.awt.UIElement", "true");
		java.awt.Toolkit.getDefaultToolkit();
		TestTrayJavaFX.main(args);
	}
}
```

The application starts correctly (no dock icon and correctly displayed tray icon)...
But after a few seconds I get this error:
```
2019-08-04 13:16:24.839 java[8586:166545] unrecognized type is 4294967295
2019-08-04 13:16:24.839 java[8586:166545] *** Assertion failure in -[NSEvent _initWithCGEvent:eventRef:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.40.119/AppKit.subproj/NSEvent.m:1977
```
And the tray becomes completely unusable.

Is there a simple way to use JavaFX and combine it with a "dockless icon" and a "SystemTray trayicon"?

**Comment by Tristan971** [comment]
What JavaFX version are you using? This seems to be a bug from the past https://stackoverflow.com/questions/52323438/assertion-failure-in-nsevent

ie you need latest JavaFX 11 or JavaFX 12, but JavaFX 8 won't work with it

**Comment by danielemaddaluno** [comment]
Yes you are right, I was still using the version 8 because is really easy packaging to a "dmg"/"app"/"exe" using the maven's [com.zenjava.javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) plugin.

I was trying to switch to the JavaFX 11 (for example using the [amazon corretto 11](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/what-is-corretto-11.html) which already includes the JavaFX) but I can't find a similar easy way to automatically package to "dmg"/"app"/"exe" etc...

Is there a way for bundling you would suggest?

**Comment by Tristan971** [comment]
It's unfortunately a bit of a pain before Java 13...
The packaging tool that zenjava's plugin uses was removed in JDK9, and the plug-in abandonned.

There's a JEP in progress to release a replacement but it's scheduled for Java 13 (or was, not sure what the state now is).

In any case, some people found ways to use experimental versions of it, for example here https://github.com/Santulator/Santulator/blob/master/package/PACKAGING.md
