### ISSUE TITLE
Plans for updating?

### ISSUE THREAD

**Issue by oxodao** [dorkbox/SystemTray#115]
Hi,

I'm starting to build a JFX app based on JDK13 (With modules, JLink, ...). I am required to have a tray icon since my software will be a screenshoting tool, thus requiring to be always in the background, and have a tray icon for other options.

I remember using this library a while back and it was pretty good, and worked great, but since it has not been updated to work on the new JDK, I probably won't be able to use it (The same goes for notify which I would really like to use again).

Do you have any plans to update these libraries ?

**Comment by dorkbox** [comment]
Sorry for the delay.

There are some plans to update these, but because of how much 9+ changed with java, it is no longer possible to do some of the things that are done -- maintaining compatibility across multiple OSes, JVMs, and architectures is no trivial matter.

There will be updates to my libraries, just not quite yet -- there's a lot going on right now and free projects are on hold until I have more time.

**Comment by oxodao** [comment]
Ok, that's cool ;) I might have to re-implement the bare minimum to do what I want 
Good luck with your other projects

**Comment by maztan** [comment]
Don't want to be a pain but when is the release of v4 planned? I am waiting eagerly :)

**Comment by dorkbox** [comment]
Release is soon, so I'm closing this support issue.
