### ISSUE TITLE
Warnings about `appindicator` are printed to `System.err`, instead of to `Logger`

### ISSUE THREAD

**Issue by kuc** [dorkbox/SystemTray#12]
Could we please have it changed to `logger.warn(...)`? (and all potential other, similar cases, if they exist)

PS: having sources of `Dorkbox-Util` library on some GitHub repo would be very handy...

**Comment by dorkbox** [comment]
Fixed in 2.1. The library isn't on GitHub (yet ... it's slowly making it's way there. It's just huge and it takes a while to verify I can release it). The sources for the parts used by the system tray are available though -- See: https://oss.sonatype.org/content/repositories/releases/com/dorkbox/SystemTray-Dorkbox-Util/2.1/

**Comment by kuc** [comment]
>The sources for the parts used by the system tray are available though -- See: https://oss.sonatype.org/content/repositories/releases/com/dorkbox/SystemTray-Dorkbox-Util/2.1/

Thanks, I'm aware of this - you mentioned this in README :wink: 
But you can't easily inspect/contribute to them in that form.
