### ISSUE TITLE
2.1: [BUG] Not working on Windows

### ISSUE THREAD

**Issue by kuc** [dorkbox/SystemTray#13]
It's trying to use `appindicator` when on Windows:

```
java.lang.RuntimeException: We apologize for this, but we are unable to determine the appIndicator library is in use, if or even if it is in use... Please create an issue for this and include your OS type and configuration.
```

**Comment by dorkbox** [comment]
Serves me right for not testing windows.... I'll have a fix up soon for that

**Comment by kuc** [comment]
_"Users are the best testers"_ :wink:

**Comment by dorkbox** [comment]
Hahaha. Definitely :)

**Comment by dorkbox** [comment]
`2.11` should work on windows now.

**Comment by kuc** [comment]
So, `2.11` works on Windows, [or not](https://github.com/dorkbox/SystemTray/issues/14#issuecomment-183933828)?

**Comment by dorkbox** [comment]
it should be. i have one that works with swt (likely just linux version of
swt)  in progress right now. I should have that up soon - it's been a busy
week.

**Comment by dorkbox** [comment]
`2.12` works much better with windows, and 2 outstanding bugs were fixed: 
 - issue with scaling images in menu
 - issue with hiding the menu when moused-out of the menu


It also works with SWT+GTK in linux (not that you use it, but now it works), and this release fixed several linux-side memory leaks (discovered when getting SWT+GTK to work).

One note about SWT+GTK, you have to force SWT to use GTK2 instead of GTK3 via `System.setProperty("SWT_GTK3", "0");`  Somehow (and I have no idea how) the methods used by SWT via GTK3 break the system tray.

Some additional properties are also available (in the readme), and I even moved over the JNA package so you can easily see how that's done.

**Comment by kuc** [comment]
:+1:
