### ISSUE TITLE
Not able to scroll the menu items inside SystemTray

### ISSUE THREAD

**Issue by mahendra-korat** [dorkbox/SystemTray#141]
I have added the System Tray successfully with more than 100 menu items which my application has. However I am not able to scroll the menu items. Am I missing anything to add scroll bar?

**Comment by dorkbox** [comment]
You're not missing anything. 100 menu items is... a lot, and honestly way more than I would have thought allowed by any OS.

I wouldn't recommend more than 10 or so in a single list, and if more are required -- a sub-menu would be the appropriate option. The official tests/examples have this if you are curious how it works.

I'm closing this because there's nothing that can be done regarding this, as it is an OS limitation (scroll bars aren't possible).

**Comment by mahendra-korat** [comment]
The normal SystemTray in Java is allowed and we were using till date and it is allowed by MAC OS, Windows & Ubuntu as least. We have decided to move on this library because Ubuntu stopped supporting the existing SystemTray of Java. However if scroll bar is not supported we will figure it out something else. Thanks for you reply.

**Comment by dorkbox** [comment]
The solution is to use a sub-menu. The "java" version creates java windows, which can have scrollbars, this library, the "SystemTray", creates native ones by calling C code.

**Comment by mahendra-korat** [comment]
No worries. Thanks for your suggestion. We will try that as well.
