### ISSUE TITLE
Is it possible to set actions when clicking the tray icon?

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#24]
What I'm looking for is a way to have it reopen my application's window when I left-click the tray icon, and open a menu when I right click the icon. Is this possible?

**Comment by dorkbox** [comment]
I wanted to have something like that as well, but unfortunately it's not possible in a cross platform way. 

Windows is one way, Mac is another, and Linux can go one way or another or both depending on the distro. It's positively mind-boggling how everyone involved (microsoft, apple, oracle, canonical, red-hat, gnome, kde) "knows what's best for the tray icon" and none of them can agree.

I'm able to work around some of the left-click VS right-click issues, but for the most part, it's entirely up to the OS to determine what is acceptable, since there are some cases where it's flat-out impossible to change the behavior. One example, is where the tray icon only responds when a menu with contents is actually opened, and only via right-click.

**Comment by brandon3055** [comment]
I understand why you wouldn't want to do this but it would be nice to have this as an option on the platforms that do support it. As long as the dev implementing this knows about its limitations it is possible to work around them. For example some of the applications i run on Ubuntu 18.04 allow you to double click the tray icon to open the main window (because double click is all that is supported) But thay also have an "Open" option in their context menu so even if the platform does not support the icon action the app is still usable.

p.s. Thanks for writing this library. Its the first thing i have found that actually works properly on Ubuntu 18.04 and most importantly for me it works along side JavaFX. The only thing i am really missing is gnome notification support.
