### ISSUE TITLE
Gnome Shell extension needs removal

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#30]

**Comment by dorkbox** [comment]
Done, and thanks for the feedback/discussion concerning this issue. 

The shell extension is no longer installed, nor is it any part of the SystemTray logic. 

**Note:** The code base and functionality is still available in this project, simply because I plan on having UI options (in a settings panel) for users to control tray icon visibility, style (native/swing) + location for my app -- and SystemTray features go in the SystemTray project.

**Comment by ashyon** [comment]
Thanks. Can you update the jar on your file server please?

**Comment by dorkbox** [comment]
Updated.
