### ISSUE TITLE
Why not use Swing containers?

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#36]
Moved from an conversation that started on a [downstream PR](https://github.com/qzind/tray/pull/149#issuecomment-269617125).

> **tresf wrote:**  I'm not particularly fond of the fact that dorkbox has chosen to reimpliment his own menu items instead of extending that which Swing already offers.  I'd rather not have dorkbox components spread all around the classes simply because he fails to implement `JMenuItem` or `AbstractButton`.

> > **dorkbox wrote:** @tresf I agree with you most of the time, but a *tiny nit* --- The `SystemTray` doesn't use Swing components for it's API (`JMenu`, `AbstractButton`, or their sub-classes) because there is undefined behavior if they were to be used without a java native peer and there is an expectation otherwise. This is an important distinction because the `SystemTray` menus and entries do not always have java native peers the way those objects expect.  I know that you understand the difference, but a quick google search for "java system tray" shows that there problems going back more than 10+ years on this topic.
> >
> > Given that a good deal of the menu system and event dispatch had to be re-implemented in a cross-platform way, I felt the best solution was a clean and concise API that doesn't leave room for ambiguity or undefined behavior. For example, if one examines the source of [AbstractButton](http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/javax/swing/AbstractButton.java) and compares it to the source for [MenuItem](https://github.com/dorkbox/SystemTray/blob/91c401e389658b10bf580796f8a6adda4575e5ec/src/dorkbox/systemTray/MenuItem.java) (or [Entry](https://github.com/dorkbox/SystemTray/blob/91c401e389658b10bf580796f8a6adda4575e5ec/src/dorkbox/systemTray/Entry.java)), it should make sense.
> >
> > Admittedly,  it pains me that the `JMenu`, etc components could not be re-used in a safe and clean way - as I wanted the `SystemTray` to be as easy for developers to use as possible, and would have preferred a 100% "drop in" replacement; ultimately the decision was reached to make sure it is absolutely clear that it is neither a Swing nor JavaFX menu. For the majority of the time, a simple change from `JMenu` -> `Menu` is sufficient, as I mirrored as much of the Swing API that was applicable.
> >
> > Please understand it wasn't a failure or ignoring advice/input, but rather a careful move on the side of caution to prevent undefined behavior and maintain a clean API.

@dorkbox can you explain why a swing-compatible container is a no-go?  

> I know that you understand the difference,

I don't think that I do.  From my very basic understanding, the library could wrap the commonly used Swing containers so that features like `setToolTipText` would be natively exposed when available (regardless of whether or not the underlying JNA supports it).  What is it about the `JMenuItem` container that can't be used to carry the icons, state, tooltip text, mnemonics, etc?

**Comment by dorkbox** [comment]
When I implemented the "peer" concept for wrapping the Swing/AWT/Gtk/AppIndicator tray icons + swing/native menus -- I initially used Swing components ([based on your previous work](https://github.com/qzind/tray/blob/2.0/src/qz/ui/tray/AWTMenuWrapper.java#L54:L56)). I ran into some problems that I had solved elsewhere, and when I found it, this was when I discovered notes about problems associated with using Swing components when accessing native (and possibly hardware accelerated) widgets.

Specifically that using a `JComponent` anywhere is one of the things that will initialize the Swing toolkit, and doing so can break the system in unexpected ways, specifically that it will *sometimes* break hardware acceleration -- and I really have no idea why other than "Swing was loaded and a butterfly flapped it's wings at the right moment".   *For the benefit of the doubt*, this was with an older version of Java, and this issue might have been resolved in 8, but I don't know. 


As I started thinking about this problem, and what I should do, it led me to think -- why **should** I use `JMenuItem` at all? I use about <5% of the `JMenuItem`/`JComponent` APIs and one could argue the API's aren't Swing API's but native API's.  The library *does* wrap a Swing based menu, but only for supporting a common set of UI elements: *separator, sub-menu, checkbox*, and *menu-item* (For my own use, I added *status item* as a *disabled* menu-item that will always sit at the top of the menu.) 

The color, font, size, layout, orientation, background, etc can't be changed - because those properties are not common across all platforms and don't always follow the defined theme. This is also why the `tooltip` is not supported by the `SystemTray` -- this library is about providing functionality for the "lowest common denominator" across all platforms, with no surprises and unexpected behavior.

Thinking about this further (and having searched the internet quite extensively for previous examples w.r.t native system tray icons/menus), I really, really don't want to field support when another developer can't figure out why `setAlignmentX` or `setAccelerator` isn't working, or when they use the `SystemTray` library for cross-platform support, and all-of-a-sudden, *feature X* isn't working like it used to.

If there is a simple and clean API - it makes the usage and behavior clear.

**Comment by dorkbox** [comment]
@tresf If tooltips are really necessary, I have [another library](https://github.com/dorkbox/Notify) that will show a small notification window (since that is cross-platform) anywhere you like on the screen. It's currently Swing-based, but I plan on adding a native version in the future as well (now that I know how to use JNA for that).

**Comment by dorkbox** [comment]
@tresf I spent part of the weekend figuring out how to solve this problem.

I tested the project (that failed with the swing components) on different versions of Java, and it only failed on Java 5. Java 6+ had no issues what-so-ever. I then went to see how I could wrap the `JMenu`, etc components -- and it turns out I didn't remove any of the wrapping methods; I thought I had removed them, and it turns out that I didn't.

So they are currently available in all of the Release Candidates, but might not behave in a way that works for you. Can you look at the [source](https://github.com/dorkbox/SystemTray/blob/master/src/dorkbox/systemTray/SystemTray.java#L991) and give me some feedback?

**Comment by tresf** [comment]
>  Can you look at the source and give me some feedback?

Thanks.  I was thrown off browsing through GitHub due to the similarity in class names (AWT Menu versus Dorkbox Menu). 

The design would work for constructing the menus but is the opposite of what is proposed in the bug description.   The bug description was really about leaving the Swing objects as-is and leveraging the well-known, common swing API as a sane method for 99% of Java desktop applications.

Since a vast majority of the design of this library is geared around the caveats around the JNA/linux library I can completely understand why a wrapper is undesired.

I'm going to close this out as it's more of a design question than a bug report.  Thanks for taking the time to explain.
