### ISSUE TITLE
Add utils class for Gtk collisions

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#46]
Since a lot of the recent work involved in perfecting this library has gone into dodging Gtk2/3 collisions, I recommend providing a utils-type class for wrapping common collision items.

For starters, the `Desktop.getDesktop()` is a dangerous call that needs to be safeguarded against.  Although we shouldn't override the system default, we can provide a helper to do the dodging for the end-user.

For example, if one wants to open the default email application, the standard method will crash when running Gtk3.  Coincidentally, this fix is already needed for certain nuances with the JDK on certain desktop environments, so to catch both scenarios, I've intentionally used `throw` to wrap both use-cases.

Pseudo-code provided.  The design and implementation may extend the `java.awt.Desktop` class for consistency purposes, etc.

```java

// e.g. function void dorkbox.utils.getDesktop.mail(URI uri) {

try {
   if (dorkbox.systemTray.jna.linux.Gtk.isGtk3) {
      throw new IOException("Avoiding Gtk2/3 collision");
   }
   Desktop.getDesktop().mail(uri);
} catch (IOException io) {
   // Some linux versions throw this naturally; Also catch intentional throw() above.
   // FIXME:  SystemUtilities and ShellUtilities would be replaced with dorkbox equivelents
   if (SystemUtilities.isUnix() && ShellUtilities.execute(new String[] {"xdg-email", uri.toString()})) {
      return;
   }
   throw io;  // rethrow original exception so that we don't steal non-Gtk3 exceptions!
}
```

Major offenders (from my own experience, there are likely others):

 * `UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());`, specifically `GTKLookAndFeel`
 * `Desktop.getDesktop().browse(...)`
 * `Desktop.getDesktop().mail(...)`
 * `Desktop.getDesktop().open(...)`

edit: formatting into a list

**Comment by dorkbox** [comment]
I'll likely have something like that. I've thought about fixing Desktop via JNA.

Thanks for the idea/input.

**Comment by dorkbox** [comment]
Additional info: https://stackoverflow.com/questions/40554515/java-swing-desktop-open-causes-gtk-error

**Comment by tresf** [comment]
@dorkbox so I ran some tests.

Turns out the `16x16` assumption was wrong from the beginning.  This is what I discovered.

100% scale factor:
 * `JMenuItem` is at natural size with an icon 10px or smaller

175% scale factor:
* `JMenuItem` is at a natural size with an icon of 16px or smaller

This explains why the 16x16 icons aren't horrible in our use-cases.  They actually fit better within the menu on HiDPI than they do on a normal DPI.

This can be observed by measuring the distance between Menu items.  In our case, "Automatically start" does not have a 16x16 icon and it appears a few pixels shorter than the rest of the items.

Unit test:
```java
// Echo a JMenuItem height as influenced by the contained ImageIcon to determine the "natural" icon size.
JFrame frame = new JFrame();
frame.setSize(100, 100);
JPopupMenu popup = new JPopupMenu();
popup.setSize(new Dimension(100, 100));
JMenuItem item = new JMenuItem("foo bar");
popup.add(item);

ArrayList<ImageIcon> icons = new ArrayList<>();
for (int i = 1; i < 128; i++) {
    icons.add(new ImageIcon(new BufferedImage(1, i, BufferedImage.TYPE_BYTE_BINARY)));
}
frame.setVisible(true);
popup.show(frame, 50, 50);

for (ImageIcon i : icons) {
    item.setIcon(i);
    item.revalidate();
    popup.setVisible(false);
    popup.show(frame, 50, 50);
    System.out.println(i.getIconHeight() + "x" + i.getIconHeight() + " icon \t>>>>>>>>> " + item.getHeight() + "px tall item");
}

```


With 100% zoom, I get this:

```diff
+7x7 icon 	>>>>>>>>> 16px tall item
+8x8 icon 	>>>>>>>>> 16px tall item
+9x9 icon 	>>>>>>>>> 16px tall item
+10x10 icon 	>>>>>>>>> 16px tall item
-11x11 icon 	>>>>>>>>> 17px tall item
-12x12 icon 	>>>>>>>>> 18px tall item
```

With 175% zoom, I get this:

```diff
+14x14 icon 	>>>>>>>>> 22px tall item
+15x15 icon 	>>>>>>>>> 22px tall item
+16x16 icon 	>>>>>>>>> 22px tall item
-17x17 icon 	>>>>>>>>> 23px tall item
-18x18 icon 	>>>>>>>>> 24px tall item
```

How does this help us?  Well, it further proves that we should be careful what assumptions we make when scaling things for end-users.

I still like the idea of the menu icons being the same size as the tray icon and I'll test the scaling logic next, but wanted to share these findings.

**Comment by tresf** [comment]
@dorkbox that example uses the same technique we do.  [Here's a list of all functions we implement](https://github.com/tresf/tray/blob/dorkbox/src/qz/utils/ShellUtilities.java), including a bug @Vzor- found with browsing withing an App bundle on Mac.   We're currently leveraging the `isGtk3` call from your API.  All Desktop-wrapper code is free to be re-released Apache 2.0

**Comment by dorkbox** [comment]
Excellent. Thank you for the list of functions.

**Comment by dorkbox** [comment]
Implemented in the [Utilities project](https://github.com/dorkbox/Utilities/blob/master/src/dorkbox/util/Desktop.java). Also uses JNA on linux instead of launching a shell command (which does not always work correctly). Additionally, one can check GTK info without initializing GTK via [OSUtil](https://github.com/dorkbox/Utilities/blob/master/src/dorkbox/util/OSUtil.java#L408).

**Comment by tresf** [comment]
The utilities class seems to offer a bunch of unrelated stuff, namely crypto and database stuff.  What does this have to do with the gtk collisions introduced with the SystrmTray library?

**Comment by dorkbox** [comment]
The [Desktop](https://github.com/dorkbox/Utilities/blob/master/src/dorkbox/util/Desktop.java) utility class (which is where GTK collisions are handled) is in the `Utilities` project and not the `SystemTray` project, because `Desktop.browseURL`, `Desktop.browseDirectory`, and `Desktop.launchEmail` have nothing to do with the SystemTray.  

This shouldn't be a concern, as the builds are intelligent and only include what is necessary - so crypto/dbase/unsigned-numbers/etc from the Utilities project that are not used, will not be included.

There's actually a lot used from the `Utilities` project by the system tray. 
 - OS
 - OSType
 - Property
 - LocationResolver
 - IO
 - FileUtil
 - ScreenUtil
 - CacheUtil
 - SwingUtil
 - FontUtil
 - OSUtil
 - MathUtil
 - ImageUtil
 - Desktop
 - JavaFX
 - Swt
 - DefaultMenuItemUI
 - DefaultSeparatorUI
 - DefaultPopupMenuUI
 - Version
 - DelayTimer
 - NamedThreadFactory
 - Keep
 - ClassLoaderUtil
 - ProcessProxy
 - NullOutputStream
 - ShellExecutor
 - ShellAsyncExecutor

**Comment by dorkbox** [comment]
I forgot to mention, SystemTray builds have appropriate utilities classes integrated into the release jar, so there is no need for an additional libarary. All of the projects are rebuilt/re-released whenever there is a relevant change to the Utilities project, so that all projects are kept in sync, should one use multiple projects.

**Comment by tresf** [comment]
Thanks for explaining.  This source-only method of building a secondary project is quite unconventional.  Projects generally do one if the following:

1. Import compiled library
2. Submodule or subtree source and include it directly

If there's ever a desire to encourage others to contribute back, I would strongly encourage adopting a method that's intuitive to other developers.

> because Desktop.browseURL, Desktop.browseDirectory, and Desktop.launchEmail have nothing to do with the SystemTray.

I understand your point, but without the JNA tricks used in SystemTray and the Gtk linking, the workarounds aren't needed (with some exceptions, such as the MacOS quirks).  They may not be related as hard dependencies, but I hope you can understand how misplaced they appear next to those other utilities.

**Comment by dorkbox** [comment]
> This source-only method of building a secondary project is quite unconventional.

Yes, and deliberately so. I reached the tipping-point about 5 years ago, where I got entirely fed up with conventional means for building projects (in my day job). Hence my own java [build](https://github.com/dorkbox/JavaBuilder) tool. Looking back, it's been worth it. It also means that you only get what you need, not 100 million other things bloating the project; obviating the need to copy files from source.

> If there's ever a desire to encourage others to contribute back  

There is, and I'll be providing detailed instructions on how to contribute in the least painful way.

&nbsp;    

> but I hope you can understand how misplaced they appear next to those other utilities.

Part of the issue is that JNA is used in multiple projects, and I was loading the same native libraries multiple times into memory (because each project was loading it's own copy).

I had a hard time deciding what to do, but since the JNA stuff is used multiple places, one of which does not have a system tray, it was really the only other place I could think for it to go. Part of JNA that is used by other projects are the Windows Event Dispatch loop and the Linux GTK Event Dispatch Loop. Once that was consolidated in the Utilities project, there was very little remaining (code-wise) for GTK specific stuff inside the SystemTray project.

**Comment by tresf** [comment]
We have this problem with bouncycastle, it's provided by two projects and when we bundle into as single, all-encompassing JAR, we get problems.  Our solution was this very poorly documented ANT trick: https://github.com/qzind/tray/commit/90565b728611b0fc5c3609b3ad440f065dd80f46#diff-2cccd7bf48b7a9cc113ff564acd802a8R42

> but since the JNA stuff is used multiple places, one of which does not have a system tray, it was really the only other place I could think for it to go.

Ok, but from an outsider looking in, it seems to offer less downstream complexities if your other project irrationally imports all of SystemTray versus the Rube-Goldberg dependency approach.

I also think you can use Git Subtree to reference a specific package folder from another project, so that might be the best of both worlds, where it can live in Utilities, but be implicitly used at clone time, then when another programmer comes along, the decision is defensible and using technologies they'll see elsewhere.

**Comment by tresf** [comment]
> I got entirely fed up with conventional means for building projects (in my day job). Hence my own java build tool. Looking back, it's been worth it. It also means that you only get what you need, not 100 million other things bloating the project;

This is quite intimidating to contributors.  Ant and Maven have their downsides, but they are well known.  If I have a Java developer that I hire, they're going to know about 12 build and dependency utilities for various languages.  They won't know one called `JavaBuilder` and this is going to add time to a project that want to work collaboratively with and upstream project with an obscure system.

If it compiles, I guess it's moot, but getting the build instructions setup is paramount if you want some good PRs to show up.

**Comment by dorkbox** [comment]
I don't expect others to use `JavaBuilder`, it was for myself. The contribution guide will be using well-known tools and processes.

I'll also look into Git Subtree.
