### ISSUE TITLE
Javassist hidden Dependency

### ISSUE THREAD

**Issue by dyorgio** [dorkbox/SystemTray#47]
Dependency bug:

I needed to include dependency on my project:
```xml
<dependency>
    <groupId>javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.12.1.GA</version>
</dependency>
```
The lib doesn't contains any maven dependency information...

**Comment by dorkbox** [comment]
Looking at the [pom](https://oss.sonatype.org/content/repositories/releases/com/dorkbox/SystemTray/3.0/SystemTray-3.0.pom) file, it shows
````
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.21.0-GA</version>
    <scope>RUNTIME</scope>
</dependency>
````

Is this incorrect? Viewing the latest javassist [here](https://oss.sonatype.org/content/repositories/releases/org/javassist/javassist/3.21.0-GA/) show's it to be accurate...

**Comment by dorkbox** [comment]
I just realized, you might have to get the file from maven for the pom info, instead of from Github releases.

**Comment by dyorgio** [comment]
@dorkbox yes, I'm using it as a maven dependency.
I will adjust to correct version, tks!

**Comment by dorkbox** [comment]
3.21.0-GA

I will also have a correct POM with all of the dependencies in the readme, which should make this process easier.

**Comment by dorkbox** [comment]
Does maven not pull the dependencies automatically when the pom is entered as follows?
````xml
<dependency>
  <groupId>com.dorkbox</groupId>
  <artifactId>SystemTray</artifactId>
  <version>3.0</version>
</dependency>
````

**Comment by dorkbox** [comment]
I ask because I thought maven pulled the deps, which are listed in the release pom.

**Comment by dyorgio** [comment]
Same problem on version 3.1, no maven metadata (pom.xml with deps) on final artifact.

**Comment by dorkbox** [comment]
Hm, something's not right -- I'm in the middle of working out some scaling issues (for a 3.2 release), and I'll figure out what's up with the pom then.

**Comment by dorkbox** [comment]
So i made some fixes, it turns out `scope case` and `newlines` have to be very specific... Also I updated the POM specification in the Readme.  These fixes were verified in a VM running the command `mvn dependency:copy-dependencies` (which just downloads all dependencies for the project).

Fixes were [here](https://github.com/dorkbox/JavaBuilder/commit/3fee727926147a9e28c9e357a431078825bc2e10) and [here](https://github.com/dorkbox/JavaBuilder/commit/75eb3a4dfb8014d805306a3d7570816b75aafb3c)

After 3.2 releases, if this is still an issue - please let me know!
