### ISSUE TITLE
Icon does not get removed immediately upon termination

### ISSUE THREAD

**Issue by AllanWang** [dorkbox/SystemTray#86]
On windows 10, setting an icon and then closing the service will leave the icon there. However, if you hover over it, it will disappear. Is it possible to clear the image in the shutdown method to see if that helps?

**Comment by dorkbox** [comment]
Unfortunately, no. What you are suggesting won't work since this is an issue with Windows itself in how it updates images. When the process crashes, it doesn't update the image. The SystemTray already has shutdown hooks in place that will run when the JVM terminates, however this doesn't help with the issue you described.

This particular bug has been present since Windows XP :(
