### ISSUE TITLE
Allow adding images from `InputStream` parameter

### ISSUE THREAD

**Issue by kuc** [dorkbox/SystemTray#9]
All methods for setting icons accepts `String` instead of `URL` (or even `InputStream`), making this task very hard...

I could even fix this myself and create PR, but you not released how to build this project into that two JARs available on maven.

**Comment by dorkbox** [comment]
I can add this real quick, no biggie (since i'm smack in the middle of it right now). So ideally it should be `String`, `URL`, and `InputStream` for the icon?

**Comment by kuc** [comment]
Thanks :smile: 

I think that ideally it could be **only** `InputStream`, because then, as library user:

- you can always convert `URL` to `InputStream` (just call `url.openStream()` ), but not the other way around :wink: 
- you can get any resource directly as `InputStream` - `this.getClass().getResourceAsStream()`
- having `File`, you can convert it to `URL` or `FileInputStream`
- having `String`, you can do any of the above to convert it to `InputStream` by yourself

**Comment by dorkbox** [comment]
Fixed in 2.1. Because I still use `String` for loading images I just added `URL` and `InputStream` (which was a great suggestion. **Thanks!**).

Please note that the appindicator tray type only takes a string (full path to the image), so the system will copy out the image to a temp file and put it in a cache to reuse (so this should only happen once). There are likely ways to wrangle it so that it works with the image directly in memory, but it's too much work to figure out the java -> native stuff, as it isn't easy.

**Comment by dorkbox** [comment]
Oh. i forgot to mention : I added support for GTK3, so the only reason libappindicator1 is necessary, is if you don't have GTK3 (which should never happen, but you never know...). Also fun thing I learned today... libappindicator1 -> GTK2, libappindicator3 -> GTK3.

**Comment by kuc** [comment]
Wow, thank you for so many useful changes :smile: 
I'm rushing to test them!

**Comment by dorkbox** [comment]
:) please do!
