### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by theangrydev** [dorkbox/SystemTray#99]
On Java 11.0.2 Ubuntu 18.04 the system tray appears to work fine but I see the following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.util.Swt (file:SystemTray-3.15.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.util.Swt
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
```

**Comment by timo-reymann** [comment]
Is there anything new on this?

**Comment by dorkbox** [comment]
I'm working on it - sadly I'm pretty swamped at work.

**Comment by dorkbox** [comment]
I am waiting on a response to this issue: https://github.com/java-native-access/jna/issues/1099

**Comment by dorkbox** [comment]
Sadly, JNA isn't accepting my pull request "because it's too hard to recompile the native binaries" for this fix. Oh well.

I'll have to remove support for re-writing classes in the 4.0 release.

**Comment by dorkbox** [comment]
Fixed this, and I've made changes so that I'm no longer using reflection (or other tricks) to see if SWT is loaded. The logic is changed slightly so that if SWT is present on the classpath, SWT will be used. JavaFX is a *little* different, where there are some additional checks before using reflection. (You can set ` System.setProperty("usingJavaFx", "true");` before setting up the SystemTray to completely avoid reflection if you are indeed wanting to use JavaFX.
